// file for flight Schema
const mongoose = require("mongoose");

const flightSchema = new mongoose.Schema({
  //_id will be used as flightID, will be the default _id generated by mongodb
  boarding: Date, // the year will be set as 2000, jan, 1 (only time is important)
  dayOfFLight: String,
  destinationAirport: String,
  flightNumber: String,
  flightType: String,
  gateClose: Date, // the year will be set as 2000, jan, 1 (only time is important)
  landingTime: Date, // the year will be set as 2000, jan, 1 (only time is important)
  price: Number, // the currency is imperial credits
  startingAirport: String,
  takeOff: Date, // the year will be set as 2000, jan, 1 (only time is important)
});

const Flight = mongoose.model("flights", flightSchema, "flights");

module.exports = Flight;
